GET http://localhost:3000/subscribers

###
GET https://www.democratrade.com/subscribers

###
GET http://localhost:3000/subscribers/62da1fe356961f832875bc3f

###

DELETE  http://localhost:3000/subscribers/62ced319086ccb395ab5402d

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Tajh",
    "email": "Tajh@email.com"
}